server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalog
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
